# -*- coding: utf-8 -*-
"""medicalCostPrediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sC29WSdSZzaA6MPRDYUL8x_gExFJRN5h
"""

import pandas as pd

df = pd.read_csv("insurance.csv")

df.head()

df.info()

y = df['charges']
X = df.drop(columns=['charges'])

X = pd.get_dummies(X, drop_first=True)

"""now train and test"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

"""train random forest regressor"""

from sklearn.ensemble import RandomForestRegressor

rf_model = RandomForestRegressor(
    n_estimators=200,
    random_state=42
)

rf_model.fit(X_train, y_train)

"""evaluate MAE

"""

from sklearn.metrics import mean_absolute_error

preds = rf_model.predict(X_test)
mae = mean_absolute_error(y_test, preds)

print("Random Forest MAE:", mae)

import pandas as pd

feature_importance = pd.Series(
    rf_model.feature_importances_,
    index=X.columns
).sort_values(ascending=False)

feature_importance

"""now actual testing of data from here"""

test_predictions = rf_model.predict(X_test)

from sklearn.metrics import mean_absolute_error

test_mae = mean_absolute_error(y_test, test_predictions)
print("Test MAE:", test_mae)

sample_person = pd.DataFrame([{
    'age': 40,
    'bmi': 30.5,
    'children': 2,
    'sex_male': 1,
    'smoker_yes': 0,
    'region_northwest': 0,
    'region_southeast': 1,
    'region_southwest': 0
}])

predicted_cost = rf_model.predict(sample_person)
print("Predicted Medical Cost:", predicted_cost[0])

comparison = pd.DataFrame({
    'Actual': y_test.values[:10],
    'Predicted': test_predictions[:10]
})

comparison

import matplotlib.pyplot as plt

plt.scatter(y_test, test_predictions)
plt.xlabel("Actual Charges")
plt.ylabel("Predicted Charges")
plt.title("Actual vs Predicted Medical Charges")
plt.show()

from sklearn.metrics import r2_score, mean_squared_error
import numpy as np

rmse = np.sqrt(mean_squared_error(y_test, test_predictions))
r2 = r2_score(y_test, test_predictions)

print("RMSE:", rmse)
print("R² Score:", r2)